// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-r6rCq1sC4Jn-4AQ9g8Ftq6PrcU23UI',
    appId: '1:785747414125:web:cfd417126a150c8b31c364',
    messagingSenderId: '785747414125',
    projectId: 'hashcode2024-7b5b5',
    authDomain: 'hashcode2024-7b5b5.firebaseapp.com',
    storageBucket: 'hashcode2024-7b5b5.appspot.com',
    measurementId: 'G-00GDF0TR60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkNoUwJ4nxxQiqj643wtc7MkxeKuLfWxI',
    appId: '1:785747414125:android:aeabc6eed88f637d31c364',
    messagingSenderId: '785747414125',
    projectId: 'hashcode2024-7b5b5',
    storageBucket: 'hashcode2024-7b5b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3CmrtRsXq17B5ry_kkT_UA1bQ6lmjNt0',
    appId: '1:785747414125:ios:79f5708281dd196331c364',
    messagingSenderId: '785747414125',
    projectId: 'hashcode2024-7b5b5',
    storageBucket: 'hashcode2024-7b5b5.appspot.com',
    iosBundleId: 'com.example.hashcode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3CmrtRsXq17B5ry_kkT_UA1bQ6lmjNt0',
    appId: '1:785747414125:ios:44fb527327669e1a31c364',
    messagingSenderId: '785747414125',
    projectId: 'hashcode2024-7b5b5',
    storageBucket: 'hashcode2024-7b5b5.appspot.com',
    iosBundleId: 'com.example.hashcode.RunnerTests',
  );
}
